services:
  server:
    image: mern-node
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "3000:3000"
  database:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      ATLAS_URI: "mongodb://mongodb:27017/myData"
